### ISSUE TITLE
version-annotator (and other processors) no longer compile under 0.882

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#297]
```
───── version-processor:compile
  Java compiling 2 files
Compilation errors, command:
javac -d processor/kobaltBuild/classes -classpath processor/kobaltBuild/classes:processor/kobaltBuild/test-classes processor/src/main/java/com/beust/version/VersionProcessor.java processor/src/main/java/com/beust/version/Version.javawarning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.8'
error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.beust.version.VersionProcessor not found
*****
***** ERROR Compilation errors, command:
javac -d processor/kobaltBuild/classes -classpath processor/kobaltBuild/classes:processor/kobaltBuild/test-classes processor/src/main/java/com/beust/version/VersionProcessor.java processor/src/main/java/com/beust/version/Version.javawarning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.8'
error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.beust.version.VersionProcessor not found
*****
```
Haven't tried with in between versions, but it compiles with 0.842

**Comment by cbeust** [comment]
The problem is that Kobalt invokes `javac` with `-d processor/kobaltBuild/classes`, which contains the processor manifest:

```
processor/kobaltBuild/classes/META-INF/services/javax.annotation.processing.Processor
```

However, the processor doesn't exist yet since it's being compiled.

Need to prevent Kobalt from adding this path at this stage of the compilation.
