### ISSUE TITLE
cannot find symbol compiling mixed project (with complex inter-class dependencies)

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#165]
compilation works fine with version 0.634 of Kobalt

```
mixed-example> cp ~/.kobalt/wrapper/dist/0.634/kobalt/wrapper/kobalt-wrapper.jar kobalt/wrapper/kobalt-wrapper.jar
mixed-example> kbw test
              __ __           __              __   __
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  0.634

Detected new installation, wiping [~]/Documents/startrack/code/mixed-example/.kobalt/build
          ╔════════════════════════╗
          ║ Building mixed-example ║
          ╚════════════════════════╝
───── mixed-example:compile
  Kotlin compiling 3 files
  Java compiling 2 files
───── mixed-example:compileTest
  Kotlin compiling 4 files
  Java compiling 3 files
───── mixed-example:test
Running tests with classpath size 21
[TestNG] Running:
  Command line suite


===============================================
Command line suite
Total tests run: 3, Failures: 0, Skips: 0
===============================================

All tests passed
BUILD SUCCESSFUL (9 seconds)
```
But not with 0.729
````
mixed-example> kbw test
              __ __           __              __   __
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  0.728

          ╔════════════════════════╗
          ║ Building mixed-example ║
          ╚════════════════════════╝
───── mixed-example:compile
  Java compiling 2 files
Compilation errors, command:
javac -d ./kobaltBuild/classes -classpath /Users/juanliska/Documents/startrack/code/mixed-example/./kobaltBuild/classes:/Users/juanliska/Documents/startrack/code/mixed-example/./kobaltBuild/test-classes:/Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-runtime/1.0.0/kotlin-runtime-1.0.0.jar:/Users/juanliska/.kobalt/repository/org/flywaydb/flyway-core/4.0/flyway-core-4.0.jar:/Users/juanliska/.kobalt/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/juanliska/.kobalt/repository/com/squareup/okhttp/okhttp/2.7.4/okhttp-2.7.4.jar:/Users/juanliska/.kobalt/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/Users/juanliska/.kobalt/repository/org/jetbrains/kotlin/kotlin-stdlib/1.0.0/kotlin-stdlib-1.0.0.jar:/Users/juanliska/.kobalt/repository/com/squareup/okio/okio/1.6.0/okio-1.6.0.jar:/Users/juanliska/.kobalt/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/juanliska/.kobalt/repository/com/squareup/okhttp/okhttp/2.7.4/okhttp-2.7.4.jar ./src/main/java/com/guatec/Example.java ./src/main/java/com/guatec/JavaBaseClass.javawarning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.8'
./src/main/java/com/guatec/Example.java:22: error: cannot find symbol
        KotlinClassThatDependsOnJavaClass kc = new KotlinClassThatDependsOnJavaClass();
        ^
  symbol:   class KotlinClassThatDependsOnJavaClass
  location: class com.guatec.Example
./src/main/java/com/guatec/Example.java:22: error: cannot find symbol
        KotlinClassThatDependsOnJavaClass kc = new KotlinClassThatDependsOnJavaClass();
                                                   ^
  symbol:   class KotlinClassThatDependsOnJavaClass
  location: class com.guatec.Example
  Kotlin compiling 3 files
BUILD FAILED: 1
````

**Comment by cbeust** [comment]
What's the problem? I can't see any error.

**Comment by pabl0rg** [comment]
sorry, i posted prematurely and had trouble getting 0.728 to run again (probably because i had .kobalt/build/buildScript.jar from 0.634)

**Comment by cbeust** [comment]
Not a bug.

You have Java classes depending on Kotlin. It only works the other way (`kotlinc` knows how to deal with Java files but not the other way around). It works if you assemble twice in a row though, since the first compilation generates the Kotlin classes before aborting. Note that even if `javac` knew how to deal with Kotlin sources, Kobalt still wouldn't know which compiler should be invoked first.

**Comment by cbeust** [comment]
You were right, it's a bug and the Kotlin compiler should indeed run first. Fixed in 0.731.
